Feature/angular13
NationalBankBelgium/ngx-form-errors pull request #46
Opened 2023-11-21 19:18 UTC by mhenkens

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows our guidelines: https://github.com/NationalBankBelgium/ngx-form-errors/blob/master/CONTRIBUTING.md#-commit-message-guidelines
-   [x] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

run on angular 8

Issue Number: N/A

## What is the new behavior?

update the library from angular 8 to angular13 and add eslint as linting engine

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2023-11-24 07:01 UTC, SuperITMan requested changes
As we discussed yesterday, could rebase your changes and leave the "ng7" and "ng8" applications alone until you have finished migrating the `ngx-form-errors` library to Angular 13 ? 
Then, upgrading both to ng12 and ng13 ?

2023-11-28 08:14 UTC, mhenkens commented on .npmrc
> +legacy-peer-deps=true
yes is still needed

2023-12-05 07:36 UTC, mhenkens commented on demo-app/ng12/test.json
not needed removed

2023-12-05 07:36 UTC, mhenkens commented on demo-app/ng13/test.json
not needed removed

2023-12-05 07:36 UTC, mhenkens commented on demo-app/ng12/package.json
> +    "start": "ng serve --disableHostCheck=true",
work removed

2023-12-05 07:37 UTC, mhenkens commented on demo-app/ng13/package.json
> +    "start": "ng serve --disableHostCheck=true",
removed

2023-12-05 07:38 UTC, mhenkens commented
> I was not able to run the ng12 demo app:
> 
> ```shell
> $ npm start                                                                                                   superitman@my-mac
> 
> > demo-app@0.0.0 start
> > ng serve --disableHostCheck=true
> 
> Warning: Running a server with --disable-host-check is a security risk. See https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a for more information.
> ⠹ Generating browser application bundles (phase: building)...node:internal/crypto/hash:69
>   this[kHandle] = new _Hash(algorithm, xofLen);
>                   ^
> 
> Error: error:0308010C:digital envelope routines::unsupported
> ```
> 
> Could you have a look ?

this issue is due to breaking change in node17 --> this work with node 14 but not node 18

see https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

2023-12-05 08:46 UTC, SuperITMan commented on package.json
> +    "angular9",
Could you change this to `"angular12", "angular13"`

2023-12-11 14:19 UTC, merged